import random from 'random';

export const sentenceTemplates = [
  '{noun} {verb} {adverb} in {noun}',
  '{noun} {verb} {adverb} along {noun}',
  '{noun} {verb} {adverb} {adjective} {noun}',
  '{noun} {verb} {noun} {adverb}',
  '{noun} {verb} in the {noun}',
  '{noun} {verb} the {noun} {adverb}',
  '{noun} {verb} {adverb} among {noun}',
  '{noun} {verb} {adverb} each {noun}',
  '{noun} {verb} {adjective} over {noun}',
  '{noun} {verb} within {adjective} {noun}',
  '{noun} {verb} against {adjective} {noun}',
  '{noun} {verb} during {noun}',
  '{noun} {verb} {adverb} on {noun}',
  '{verb} {noun} along {adjective} {noun}',
  '{noun} {verb} {adverb} {noun}',
  '{noun} {verb} around {noun}',
  '{noun} {verb} {noun} in {noun}',
  '{noun} {verb} across {adjective} {noun}',
  '{noun} {verb} {adverb} in {adjective} {noun}',
  '{noun} are {verb} along {noun}',
  '{noun} {verb} with {noun}',
  '{noun} are {verb} with {noun}',
  '{noun} {verb} {noun} {verb}',
  '{noun} {verb} from {adjective} {noun}',
  '{noun} {verb} {adjective} {noun}',
  '{noun} {verb} in {verb} {noun}',
  '{noun} {verb} {adverb} {adverb}',
  '{noun} {verb} {verb} on {noun}',
  '{noun} {verb} till {verb} {noun} ',
  '{noun} {verb} to {adjective} {noun}',
  '{noun} {verb} with {adjective} {noun}',
  '{noun} {verb} {adverb} across {noun}',
  '{noun} {verb} {noun} more {adverb}',
  '{noun} {verb} {adverb} {adjective}',
  '{noun} {verb} {noun} and {noun}',
  '{noun} {verb} till {verb} {adjective} {noun}',
  '{noun} {verb} {adverb} {adjective} over {noun}',
  '{noun} {verb} due to {adjective} {noun}',
  '{noun} {verb} into {adjective} {noun}',
  '{noun} {verb} {adjective} {noun} {adverb}',
  '{noun} will {verb} {adjective} {noun}',
  '{adjective} {noun} {noun} will {verb} {noun}',
  '{adjective} {noun} will {verb} {adjective} {noun}',
  '{adjective} {noun} will {verb} {noun}',
  '{noun} will {verb} {noun} {adverb}',
  '{noun} will {verb} {noun}',
  '{noun} will {verb} {adverb} {adjective}',
  '{adjective} {noun} will {verb} {noun} {noun}',
  '{noun} will {verb} {noun} {noun}',
  '{noun} will {verb} {noun} {adjective} {noun}',
  '{adjective} {noun} will {verb} {noun} {adverb}',
  '{noun} {noun} will {noun} {noun}',
  '{noun} {noun} will {verb} {adjective} {noun}',
  '{noun} will enable {adverb} {noun}',
  '{adjective} {noun} will reduce {adjective} {noun}',
];

// export const phrases = [
//   'In the morning ',
//   'After school ',
//   'At work ',
//   'On the road ',
//   'Under the table ',
//   'Over the hill ',
//   'Before bedtime ',
//   'During lunchtime ',
//   'Near the park ',
//   'Across the street ',
//   'Behind the house ',
//   'Inside the box ',
//   'Outside the store ',
//   'Around the corner ',
//   'By the river ',
//   'Against the wall ',
//   'Through the window ',
//   'Without a doubt ',
//   'With my friends ',
//   'Without hesitation ',
//   'Within reach ',
//   'Throughout the day ',
//   'Along the path ',
//   'Among the trees ',
//   'Beneath the surface ',
//   'Behind closed doors ',
//   'Above the clouds ',
//   'After dark ',
//   'Amidst the chaos ',
//   'Alongside the road ',
//   'Between the lines ',
//   'Below the surface ',
//   'Behind the scenes ',
//   'Beyond compare ',
//   'By all means ',
//   'Despite the odds ',
//   'During the storm ',
//   'Inside out ',
//   'In the spotlight ',
//   'Into the unknown ',
//   'On the contrary ',
//   'On the way ',
//   'Out of reach ',
//   'Outside the box ',
//   'Throughout history ',
//   'Upon arrival ',
//   'With open arms ',
//   'With great care ',
//   'Within minutes ',
//   'Without question ',
// ];

const nouns = [
  'dune',
  'time',
  'thing',
  'part',
  'world',
  'place',
  'week',
  'state',
  'fact',
  'side',
  'interest',
  'book',
  'form',
  'market',
  'result',
  'rate',
  'office',
  'view',
  'year',
  'child',
  'work',
  'system',
  'group',
  'house',
  'problem',
  'hand',
  'country',
  'member',
  'head',
  'home',
  'power',
  'water',
  'idea',
  'report',
  'face',
  'road',
  'right',
  'term',
  'case',
  'number',
  'area',
  'point',
  'night',
  'change',
  'other',
  'level',
  'effect',
  'name',
  'line',
  'reason',
  'period',
  'price',
  'cost',
  'moment',
  'force',
  'act',
  'mind',
  'paper',
  'section',
  'table',
  'sense',
  'team',
  'plan',
  'practice',
  'letter',
  'food',
  'event',
  'teacher',
  'material',
  'example',
  'manager',
  'worker',
  'nature',
  'million',
  'control',
  'issue',
  'type',
  'matter',
  'death',
  'union',
  'trade',
  'range',
  'parent',
  'care',
  'data',
  'need',
  'kind',
  'action',
  'process',
  'minute',
  'value',
  'class',
  'staff',
  'student',
  'town',
  'product',
  'game',
  'role',
  'stage',
  'voice',
  'field',
  'record',
  'model',
  'method',
  'unit',
  'date',
  'amount',
  'award',
  'chapter',
  'test',
  'election',
  'future',
  'shop',
  'love',
  'pattern',
  'fire',
  'size',
  'attention',
  'demand',
  'sea',
  'choice',
  'player',
  'feature',
  'mile',
  'task',
  'movement',
  'wall',
  'president',
  'change',
  'share',
  'site',
  'factor',
  'music',
  'design',
  'leader',
  'operation',
  'charge',
  'pressure',
  'garden',
  'rest',
  'region',
  'relation',
  'statement',
  'capital',
  'village',
  'machine',
  'function',
  'sound',
  'floor',
  'response',
  'user',
  'look',
  'bill',
  'glass',
  'claim',
  'park',
  'aspect',
  'summer',
  'stone',
  'client',
  'affair',
  'version',
  'return',
  'talk',
  'trouble',
  'article',
  'card',
  'style',
  'skill',
  'title',
  'river',
  'sector',
  'seat',
  'appeal',
  'item',
  'show',
  'press',
  'star',
  'second',
  'chair',
  'season',
  'element',
  'increase',
  'note',
  'measure',
  'post',
  'image',
  'goal',
  'speaker',
  'deal',
  'text',
  'payment',
  'earth',
  'agency',
  'weight',
  'target',
  'forest',
  'crime',
  'review',
  'speech',
  'owner',
  'cash',
  'shape',
  'master',
  'vote',
  'fear',
  'edge',
  'stock',
  'match',
  'corner',
  'message',
  'scale',
  'sport',
  'partner',
  'farm',
  'past',
  'start',
  'move',
  'english',
  'driver',
  'meaning',
  'adult',
  'play',
  'damage',
  'opinion',
  'rock',
  'option',
  'whole',
  'network',
  'finger',
  'race',
  'peace',
  'scene',
  'failure',
  'reader',
  'file',
  'safety',
  'trial',
  'copy',
  'nation',
  'doubt',
  'train',
  'reform',
  'agent',
  'pair',
  'rise',
  'queen',
  'danger',
  'path',
  'video',
  'content',
  'boat',
  'prison',
  'wine',
  'battle',
  'farmer',
  'package',
  'painting',
  'mountain',
  'meal',
  'traffic',
  'session',
  'route',
  'impact',
  'flower',
  'reaction',
  'comment',
  'reality',
  'winter',
  'phone',
  'author',
  'engine',
  'manner',
  'victim',
  'tour',
  'wood',
  'flat',
  'sheet',
  'code',
  'loan',
  'flight',
  'speed',
  'track',
  'gold',
  'skin',
  'offer',
  'write',
  'expert',
  'sample',
  'smile',
  'relief',
  'wage',
  'dinner',
  'asset',
  'limit',
  'dream',
  'selection',
  'decade',
  'middle',
  'module',
  'desire',
  'block',
  'noise',
  'heat',
  'theme',
  'rain',
  'spring',
  'output',
  'tape',
  'error',
  'waste',
  'screen',
  'phase',
  'gate',
  'finance',
  'neck',
  'store',
  'grant',
  'pleasure',
  'weather',
  'pool',
  'location',
  'drive',
  'flow',
  'release',
  'passage',
  'device',
  'request',
  'creation',
  'present',
  'ticket',
  'soldier',
  'lake',
  'enemy',
  'nose',
  'height',
  'castle',
  'motion',
  'total',
  'winner',
  'strike',
  'desk',
  'fashion',
  'beach',
  'motor',
  'servant',
  'editor',
  'palace',
  'trend',
  'plastic',
  'fault',
  'pilot',
  'stress',
  'frame',
  'holder',
  'saving',
  'shock',
  'meter',
  'novel',
  'taste',
  'gene',
  'string',
  'warning',
  'knee',
  'living',
  'signal',
  'plane',
  'score',
  'tenant',
  'topic',
  'break',
  'female',
  'port',
  'mode',
  'autumn',
  'camera',
  'guard',
  'suit',
  'drama',
  'steel',
  'zone',
  'dozen',
  'final',
  'jacket',
  'apple',
  'dance',
  'export',
  'average',
  'silver',
  'bread',
  'cloud',
  'mood',
  'actor',
  'estimate',
  'rent',
  'secret',
  'dealer',
  'load',
  'layer',
  'sleep',
  'cake',
  'soul',
  'coach',
  'chip',
  'reply',
  'duke',
  'routine',
  'fight',
  'hearing',
  'delay',
  'remark',
  'emotion',
  'carpet',
  'hero',
  'sand',
  'cream',
  'count',
  'mine',
  'anger',
  'disk',
  'mail',
  'rank',
  'tale',
  'scope',
  'clock',
  'joke',
  'sake',
  'moon',
  'snow',
  'wish',
  'drop',
  'label',
  'grade',
  'shell',
  'stake',
  'wire',
  'complex',
  'mouse',
  'reward',
  'local',
  'storage',
  'import',
  'lover',
  'steam',
  'tunnel',
  'movie',
  'black',
  'check',
  'fellow',
  'margin',
  'pole',
  'stand',
  'ward',
  'cold',
  'flesh',
  'good',
  'nerve',
  'coin',
  'folk',
  'paint',
  'stick',
  'lease',
  'ocean',
  'summit',
  'leather',
  'alarm',
  'craft',
  'mate',
  'audit',
  'trick',
  'domain',
  'bike',
  'stranger',
  'angel',
  'dose',
  'fate',
  'resort',
  'shade',
  'rope',
  'escape',
  'gear',
  'temple',
  'gender',
  'skit',
];

const adjectives = [
  'great',
  'large',
  'right',
  'late',
  'clear',
  'black',
  'easy',
  'wide',
  'find',
  'nice',
  'cold',
  'deep',
  'cheap',
  'wild',
  'fast',
  'new',
  'high',
  'early',
  'dead',
  'ready',
  'fair',
  'safe',
  'warm',
  'very',
  'bright',
  'slow',
  'empty',
  'bloody',
  'clean',
  'rare',
  'small',
  'fair',
  'real',
  'strong',
  'poor',
  'close',
  'alone',
  'grand',
  'weak',
  'near',
  'glad',
  'dear',
  'place',
  'sad',
  'remote',
  'still',
  'tight',
  'welcome',
  'blind',
  'clever',
  'loud',
  'modest',
  'faint',
  'spare',
  'steep',
  'mild',
  'vast',
  'lucky',
  'yellow',
  'flat',
  'cool',
  'wise',
  'acute',
  'neat',
  'damp',
  'casual',
  'sick',
  'well',
  'keen',
  'mere',
  'mad',
  'plain',
  'pleasant',
  'mean',
  'raw',
  'just',
  'crazy',
  'secure',
  'mature',
  'drunk',
  'bold',
  'rear',
  'calm',
  'fond',
  'rude',
  'sore',
  'petty',
  'sexy',
  'fancy',
  'slim',
  'grim',
  'sandy',
  'weary',
  'foul',
  'sour',
  'smart',
  'sound',
  'polite',
  'lazy',
  'lean',
  'dim',
];

const verbs = [
  'feel',
  'keep',
  'play',
  'meet',
  'stand',
  'talk',
  'read',
  'lose',
  'fall',
  'send',
  'have',
  'mean',
  'work',
  'seem',
  'like',
  'start',
  'lead',
  'offer',
  'remain',
  'speak',
  'build',
  'return',
  'make',
  'know',
  'come',
  'tell',
  'need',
  'ask',
  'allow',
  'change',
  'stop',
  'decide',
  'draw',
  'walk',
  'base',
  'cover',
  'form',
  'fail',
  'love',
  'argue',
  'arrive',
  'plan',
  'close',
  'thank',
  'express',
  'save',
  'control',
  'sell',
  'pass',
  'apply',
  'learn',
  'stay',
  'deal',
  'rise',
  'pick',
  'prove',
  'enter',
  'relate',
  'note',
  'wonder',
  'tend',
  'share',
  'create',
  'wait',
  'raise',
  'claim',
  'cut',
  'contain',
  'seek',
  'face',
  'end',
  'drive',
  'place',
  'wear',
  'present',
  'refer',
  'affect',
  'avoid',
  'remove',
  'admin',
  'prepare',
  'drop',
  'prevent',
  'depend',
  'check',
  'sound',
  'extend',
  'define',
  'attend',
  'adopt',
  'mind',
  'settle',
  'force',
  'replace',
  'refuse',
  'reveal',
  'enable',
  'arise',
  'result',
  'stare',
];

const adverbs = [
  'daily',
  'hard',
  'fast',
  'well',
  'easily',
  'closely',
  'yet',
  'today',
  'then',
  'still',
  'since',
  'soon',
  'rarely',
  'often',
  'now',
  'next',
  'never',
  'later',
  'last',
  'just',
  'first',
  'ever',
  'finally',
  'early',
  'before',
  'always',
  'above',
  'below',
  'down',
  'under',
  'back',
  'always',
  'about',
  'east',
  'here',
  'inside',
  'near',
  'north',
  'south',
  'there',
  'west',
  'where',
  'almost',
  'too',
  'very',
  'really',
  'much',
  'most',
  'less',
  'little',
  'least',
];

function makeRandomSentence() {
  let currentWord: { type: string | undefined; value: string | undefined } = {
    type: undefined,
    value: undefined,
  };

  const template = random.choice(sentenceTemplates) || '';

  const templateList = template.split(' ').map((word) => {
    let value: string | undefined = word;

    if (word === '{noun}') {
      value =
        currentWord.type === word
          ? random.choice(nouns.filter((noun) => noun !== currentWord.value))
          : random.choice(nouns);
    } else if (word === '{adjective}') {
      value =
        currentWord.type === word
          ? random.choice(
              adjectives.filter((noun) => noun !== currentWord.value),
            )
          : random.choice(adjectives);
    } else if (word === '{verb}') {
      value =
        currentWord.type === word
          ? random.choice(verbs.filter((noun) => noun !== currentWord.value))
          : random.choice(verbs);
    } else if (word === '{adverb}') {
      value =
        currentWord.type === word
          ? random.choice(adverbs.filter((noun) => noun !== currentWord.value))
          : random.choice(adverbs);
    }

    currentWord = { type: word, value };

    return value;
  });

  return templateList.join(' ');
}

export function createSentence() {
  // const phrase = getRandomStartingPhrase();
  // const sentence = phrase
  //   ? `${phrase} ${makeRandomSentence()}`
  //   : makeRandomSentence();

  const sentence = makeRandomSentence();
  return sentence.replace(/[^a-zA-Z ]/g, '').toLowerCase();
}
